const dir = [
    {
        direction: "全部",
    },
    {
        direction: "前沿技术",
    },
    {
        direction: "前端开发",
    },
    {
        direction: "前沿技术",
    },
    {
        direction: "后端开发",
    },
    {
        direction: "移动开发",
    },
    {
        direction: "算法&数学",
    },
    {
        direction: "云计算&大数据",
    },
    {
        direction: "运维&测试",
    },
    {
        direction: " 数据库",
    },
    {
        direction: "UI设计&多媒体",
    },
    {
        direction: "游戏",
    },
]
const type = [
    {
        type:'全部',
    },

    {
        type:"PHP",
    },
    {
        type:"C",
    },
    {
        type:"C++",
    },
    {
        type:"C#",
    },
    {
        type:"Ruby",
    },
    {
        type:"Android",
    },
    {
        type:"iOS",
    },
    {
        type:"React native",
    },
    {
        type:"WEEX",
    },
    {
        type:"算法与数据结构",
    },
    {
        type:"数学",
    },
    {
        type:"大数据",
    },
    {
        type:"Hadoop",
    },
    {
        type:"Spark",
    },
    {
        type:"Hbase",
    },
    {
        type:"Storm",
    },
    {
        type:"云计算",
    },
    {
        type:"AWS",
    },
    {
        type:"Docker",
    },
    {
        type:"Kubernetes",
    },
    {
        type:"运维",
    },
    {
        type:"自动化运维",
    },
    {
        type:"运维工具",
    },
    {
        type:"Linux",
    },
    {
        type:"测试",
    },
    {
        type:"功能测试",
    },
    {
        type:"性能测试",
    },
    {
        type:"自动化测试",
    },
    {
        type:"接口测试",
    },
    {
        type:"安全测试",
    },
    {
        type:"MySQL",
    },
    {
        type:"Redis",
    },
    {
        type:"MongoDB",
    },
    {
        type:"Oracle",
    },
    {
        type:"SQL Server",
    },
    {
        type:"模型制作",
    },
    {
        type:"动效动画",
    },
    {
        type:"设计基础",
    },
    {
        type:"设计工具",
    },
    {
        type:"APPUI设计",
    },
    {
        type:"产品交互",
    },
    {
        type:"Unity 3D",
    },
    {
        type:"Cocos2d-x",
    },
    {
        type:"Html5",
    },
    {
        type:"CSS3",
    },
    {
        type:"NoSql",
    },
    {
        type:"Photoshop",
    },
    {
        type:'全部',
    },
    {
        type:'微服务',
    },
    {
        type:'区块链',
    },

    {
        type:'以太坊',
    },
    {
        type:'以太坊',
    },
    {
        type:'以太坊',
    },
    {
        type:'人工智能',
    },
    {
        type:'机器学习',
    },
    {
        type:'深度学习',
    },
    {
        type:'计算机视觉',
    },
    {
        type:'自然语言处理',
    },
    {
        type:'数据分析&挖掘',
    },
    {
        type:'HTML/CSS',
    },
    {
        type:'JavaScript',
    },
    {
        type:'Vue.js',
    },
    {
        type:'React.JS',
    },
    {
        type:'Angular',
    },
    {
        type:'Node.js',
    },
    {
        type:'jQuery',
    },
    {
        type:'Bootstrap',
    },
    {
        type:'Sass/Less',
    },
    {
        type:'WebApp',
    },
    {
        type:'前端工具',
    },
    {
        type:'Java',
    },
    {
        type:'SpringBoot',
    },
    {
        type:'Python',
    },
    {
        type:'爬虫',
    },
    {
        type:"Django",
    },
    {
        type:"Tornado",
    },
    {
        type:"Go",
    }
]
const difficulty=[
    {
        difficulty:'全部',
    },
    {
        difficulty:'入门',
    },
    {
        difficulty:'初级',
    },
    {
        difficulty:'中级',
    },
    {
        difficulty:'高级',
    }
]
const con = [
    {
        type:"Tornado",
        pic:"./img/free/course/1.jpg",
        title:"初识HTML+CSS",
        grade:"高级",
        people:"2000",
        content:"HTML+CSS基础教程8小时带领大家步步深入学习标签用法和意义",
    },
    {
        type:"Tornado",
        pic:"./img/free/course/2.jpg",
        title:"Java入门第一季",
        grade:"中级",
        people:"3000",
        content:"本教程从Java环境搭建、工具使用、基础语法开始，带你入门",
    },
    {
        type:"Tornado",
        pic:"./img/free/course/3.jpg",
        title:"C语言入门",
        grade:"中级",
        people:"4000",
        content:"C语言入门视频教程，带你进入编程世界的必修课-C语言",
    },
    {
        type:"Tornado",
        pic:"./img/free/course/4.jpg",
        title:"JavaScript入门篇",
        grade:"中级",
        people:"5000",
        content:"JavaScript做为一名Web工程师的必备技术，本教程让您快速入门",
    },
    {
        type:"Tornado",
        pic:"./img/free/course/5.jpg",
        title:"初识Python",
        grade:"中级",
        people:"6000",
        content:"学python入门视频教程，让你快速入门并能编写简单的Python程序",
    },
    {
        type:'Sass/Less',
        pic:"./img/free/course/6.jpg",
        title:"PS入门教程——新手过招",
        grade:"高级",
        people:"2000",
        content:"HTML+CSS基础教程8小时带领大家步步深入学习标签用法和意义",
    },
    {
        type:'Sass/Less',
        pic:"./img/free/course/7.jpg",
        title:"探索MG动画的神奇世界",
        grade:"低级",
        people:"3000",
        content:"本教程从Java环境搭建、工具使用、基础语法开始，带你入门",
    },
    {
        type:'Sass/Less',
        pic:"./img/free/course/8.jpg",
        title:"Kingshard数据库中间件理论与实践",
        grade:"低级",
        people:"4000",
        content:"C语言入门视频教程，带你进入编程世界的必修课-C语言",
    },
    {
        type:'Sass/Less',
        pic:"./img/free/course/9.jpg",
        title:"Python 高性能 Web 框架 Tornado入门",
        grade:"低级",
        people:"5000",
        content:"JavaScript做为一名Web工程师的必备技术，本教程让您快速入门",
    },
    {
        type:'Sass/Less',
        pic:"./img/free/course/10.jpg",
        title:"绑定基础",
        grade:"低级",
        people:"6000",
        content:"学python入门视频教程，让你快速入门并能编写简单的Python程序",
    },
    {
        type:'爬虫',
        pic:"./img/free/course/11.jpg",
        title:"MBE风格图标设计",
        grade:"高级",
        people:"2000",
        content:"HTML+CSS基础教程8小时带领大家步步深入学习标签用法和意义",
    },
    {
        type:'爬虫',
        pic:"./img/free/course/12.jpg",
        title:"React高级教程之高阶组件",
        grade:"入门",
        people:"3000",
        content:"本教程从Java环境搭建、工具使用、基础语法开始，带你入门",
    },
    {
        type:'爬虫',
        pic:"./img/free/course/13.jpg",
        title:"MUI+个推实现安卓与ios移动端推送",
        grade:"入门",
        people:"4000",
        content:"C语言入门视频教程，带你进入编程世界的必修课-C语言",
    },
    {
        type:'爬虫',
        pic:"./img/free/course/14.jpg",
        title:"2018 AWS技术峰会  自动化运维、微服务及容器技术分论坛",
        grade:"入门",
        people:"5000",
        content:"JavaScript做为一名Web工程师的必备技术，本教程让您快速入门",
    },
    {
        type:'爬虫',
        pic:"./img/free/course/15.jpg",
        title:"基于LNMP的测试工具环境部署",
        grade:"入门",
        people:"6000",
        content:"学python入门视频教程，让你快速入门并能编写简单的Python程序",
    },
    {
        type:"PHP",
        pic:"./img/free/course/16.jpg",
        title:"Sqoop入门实践",
        grade:"高级",
        people:"2000",
        content:"HTML+CSS基础教程8小时带领大家步步深入学习标签用法和意义",
    },
    {
        type:"PHP",
        pic:"./img/free/course/17.jpg",
        title:"深度学习之神经网络入门最佳路径",
        grade:"初级",
        people:"3000",
        content:"本教程从Java环境搭建、工具使用、基础语法开始，带你入门",
    },
    {
        type:"PHP",
        pic:"./img/free/course/18.jpg",
        title:"自然语言处理（NLP）入门与实践",
        grade:"初级",
        people:"4000",
        content:"C语言入门视频教程，带你进入编程世界的必修课-C语言",
    },
    {
        type:"PHP",
        pic:"./img/free/course/19.jpg",
        title:"社交类app设计入门",
        grade:"初级",
        people:"5000",
        content:"JavaScript做为一名Web工程师的必备技术，本教程让您快速入门",
    },
    {
        type:"PHP",
        pic:"./img/free/course/20.jpg",
        title:"redis计数器与数量控制",
        grade:"初级",
        people:"6000",
        content:"学python入门视频教程，让你快速入门并能编写简单的Python程序",
    },
    {
        type:"PHP",
        pic:"./img/free/course/21.jpg",
        title:"iris+xorm Go语言开发球星库",
        grade:"高级",
        people:"2000",
        content:"HTML+CSS基础教程8小时带领大家步步深入学习标签用法和意义",
    },
    {
        type:'Bootstrap',
        pic:"./img/free/course/22.jpg",
        title:"Springboot 微信小程序 – 微信登录功能实战",
        grade:"高级",
        people:"3000",
        content:"本教程从Java环境搭建、工具使用、基础语法开始，带你入门",
    },
    {
        type:'Bootstrap',
        pic:"./img/free/course/23.jpg",
        title:"MAYA-角色走跑动画",
        grade:"高级",
        people:"4000",
        content:"C语言入门视频教程，带你进入编程世界的必修课-C语言",
    },
    {
        type:'Bootstrap',
        pic:"./img/free/course/24.jpg",
        title:"Android性能优化之图片优化",
        people:"5000",
        grade:"高级",
        content:"JavaScript做为一名Web工程师的必备技术，本教程让您快速入门",
    },
    {
        type:'Bootstrap',
        pic:"./img/free/course/25.jpg",
        title:"2018 AWS技术峰会 人工智能分论坛",
        people:"6000",
        grade:"高级",
        content:"学python入门视频教程，让你快速入门并能编写简单的Python程序",
    },
    {
        type:'Bootstrap',
        pic:"./img/free/course/26.jpg",
        title:"移动界面设计",
        grade:"高级",
        people:"2000",
        content:"HTML+CSS基础教程8小时带领大家步步深入学习标签用法和意义",
    },
    {
        type:'WebApp',
        pic:"./img/free/course/27.jpg",
        title:"React 16实现订单列表及评价功能",
        grade:"初级",
        people:"3000",
        content:"本教程从Java环境搭建、工具使用、基础语法开始，带你入门",
    },
    {
        type:'WebApp',
        pic:"./img/free/course/28.jpg",
        title:"Flink入门",
        grade:"低级",
        people:"4000",
        content:"C语言入门视频教程，带你进入编程世界的必修课-C语言",
    },
    {
        type:'WebApp',
        pic:"./img/free/course/29.jpg",
        title:"使用Beego构建完整web项目",
        grade:"中级",
        people:"5000",
        content:"JavaScript做为一名Web工程师的必备技术，本教程让您快速入门",
    },
    {
        type:'WebApp',
        pic:"./img/free/course/30.jpg",
        title:"Spring Boot 2.0深度实践之系列总览",
        grade:"初级",
        people:"6000",
        content:"学python入门视频教程，让你快速入门并能编写简单的Python程序",
    },
]